language: node_js
node_js:
  - "8"
sudo: required
dist: trusty
install:
  - "npm install"
script:
  - "npm run build"
  - "echo '/ /html/multipage/' > output/_redirects"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: false
  local-dir: output/html
  on:
    branch: master
