language: node_js
node_js:
  - "8"
sudo: required
dist: trusty
install:
  - "npm install"
script:
  - "npm run build"
  - "echo '/ /html/multipage/' > output/_redirects"
deploy:
  provider: script
  skip_cleanup: true
  script: "npm run deploy"
  on:
    branch: master
