language: node_js
node_js:
  - "8"
sudo: required
dist: trusty
env:
  - LAZ_VER=3.0.0
  - "PATH=$PATH:`pwd`/wattsi/bin"
install:
  - "npm install"
  - "git submodule add https://github.com/nielsAD/travis-lazarus.git travis-lazarus"
  - "./travis-lazarus/.travis.install.py"
  - "git submodule add https://github.com/whatwg/wattsi.git wattsi"
  - "cd wattsi && ./build.sh"
script:
  - "npm run build"
