language: node_js
dist: bionic
node_js:
  - "8"
sudo: required
before_install:
  - sudo apt-get update;
    sudo apt-get install -y --no-install-recommends fpc
install:
  - "npm install"
script:
  - "npm run build"
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: false
  local-dir: output/html
  on:
    branch: master
